const state={lang:"id",cart:[],slide:0};
const slides=[...document.querySelectorAll(".slide")];
const labels=["The Niffalla Collection","Hydra Gentle Cleanser","Moisture Daily Cream","Calm Soothing Toner","Glow Brightening Serum"];
const dots=document.getElementById("dots");
slides.forEach((_,i)=>{const b=document.createElement("button");b.setAttribute("aria-label","Slide "+(i+1));b.addEventListener("click",()=>showSlide(i));dots.appendChild(b)});
function showSlide(i){state.slide=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle("active",n===state.slide));[...dots.children].forEach((d,n)=>d.classList.toggle("active",n===state.slide));document.getElementById("slideLabel").textContent=labels[state.slide]}
showSlide(0);
document.querySelector(".next").onclick=()=>showSlide(state.slide+1);
document.querySelector(".prev").onclick=()=>showSlide(state.slide-1);
setInterval(()=>showSlide(state.slide+1),5000);

const dict={
id:{topbar:"Free shipping untuk pembelian pilihan • Kulit sehat, hati lebih tenang ✦",nav_home:"Home",nav_products:"Products",nav_about:"About",nav_promo:"Promo",nav_journal:"Journal",nav_contact:"Contact",hero_eyebrow:"A gentle ritual for your skin",hero_script:"Kulit sehat, hati pun lebih tenang.",hero_text:"Perawatan lembut yang dirancang untuk menemani ritual kecantikanmu setiap hari.",shop_now:"Shop Collection",discover:"Discover Niffalla",trust1:"Hydrating Formula",trust2:"All Skin Types",trust3:"Gentle Care",about_eyebrow:"THE NIFFALLA PHILOSOPHY",about_title:"Inner Beauty dimulai dari perawatan yang lembut.",about_text:"Kami percaya merawat kulit bukan sekadar rutinitas, tetapi momen kecil untuk kembali mencintai diri sendiri.",benefit1_title:"Hydrate",benefit1_text:"Membantu menjaga kelembapan agar kulit terasa lembut dan nyaman.",benefit2_title:"Glow",benefit2_text:"Mendukung tampilan kulit yang tampak lebih cerah dan fresh.",benefit3_title:"Soothe",benefit3_text:"Formula lembut untuk ritual skincare yang menenangkan.",benefit4_title:"Balance",benefit4_text:"Perawatan sederhana untuk menemani semua jenis kulit setiap hari.",products_title:"Temukan ritual Niffalla-mu",products_text:"Pilihan skincare essentials untuk membersihkan, menenangkan, melembapkan, dan membuat kulit tampak glowing.",cleanser_desc:"Bersihkan kulit tanpa terasa kering.",toner_desc:"Hydrate, soothe, dan bantu menjaga keseimbangan kulit.",serum_desc:"Bantu kulit tampak lebih cerah dan glowing.",cream_desc:"Kunci kelembapan dengan rasa nyaman sepanjang hari.",add_cart:"Tambah",promo_title:"Soft glow-mu dimulai dari sini.",promo_text:"Nikmati penawaran spesial untuk memulai ritual Niffalla-mu.",promo_use:"Gunakan kode",copy:"Salin Kode",routine_title:"Sedikit ritual, sedikit lebih glowing.",step1:"Cleanse",step1_text:"Mulai dengan membersihkan wajah secara lembut.",step2:"Prepare",step2_text:"Segarkan dan siapkan kulit dengan toner.",step3:"Treat",step3_text:"Gunakan serum sebagai langkah perawatan intensif.",step4:"Moisturize",step4_text:"Kunci kelembapan agar kulit terasa nyaman.",journal_title:"Catatan kecil untuk kulitmu.",read_more:"Baca lebih banyak →",article1:"Cara membangun rutinitas skincare yang sederhana",article1_text:"Tidak perlu banyak langkah untuk memulai perawatan yang konsisten.",article2:"Mengapa kulit juga butuh waktu untuk beristirahat",article2_text:"Rawat kulit dengan lembut dan dengarkan apa yang dibutuhkannya.",article3:"Glow yang baik dimulai dari ritual kecil",article3_text:"Buat momen merawat diri terasa lebih tenang dan bermakna.",newsletter_title:"Sedikit beauty note, khusus untukmu.",subscribe:"Berlangganan",cart_title:"Ritual Niffalla-mu",empty_cart:"Keranjangmu masih kosong.",total:"Total",checkout:"Checkout via WhatsApp",wa_chat:"Chat dengan kami",footer_text:"Gentle skincare ritual for your everyday glow.",privacy:"Privasi",follow:"FOLLOW THE GLOW",rights:"All rights reserved."},
en:{topbar:"Free shipping on selected purchases • Healthy skin, a calmer heart ✦",nav_home:"Home",nav_products:"Products",nav_about:"About",nav_promo:"Promo",nav_journal:"Journal",nav_contact:"Contact",hero_eyebrow:"A gentle ritual for your skin",hero_script:"Healthy skin, a calmer heart.",hero_text:"Gentle care designed to accompany your beauty ritual every day.",shop_now:"Shop Collection",discover:"Discover Niffalla",trust1:"Hydrating Formula",trust2:"All Skin Types",trust3:"Gentle Care",about_eyebrow:"THE NIFFALLA PHILOSOPHY",about_title:"Inner Beauty starts with gentle care.",about_text:"We believe skincare is more than a routine; it is a small moment to return to loving yourself.",benefit1_title:"Hydrate",benefit1_text:"Helps maintain moisture so skin feels soft and comfortable.",benefit2_title:"Glow",benefit2_text:"Supports a brighter, fresher-looking complexion.",benefit3_title:"Soothe",benefit3_text:"A gentle formula for a calming skincare ritual.",benefit4_title:"Balance",benefit4_text:"Simple care made to accompany all skin types every day.",products_title:"Find your Niffalla ritual",products_text:"Skincare essentials to cleanse, soothe, hydrate, and support a healthy-looking glow.",cleanser_desc:"Cleanse without leaving skin feeling dry.",toner_desc:"Hydrate, soothe, and help maintain skin balance.",serum_desc:"Helps skin look brighter and more radiant.",cream_desc:"Lock in moisture for everyday comfort.",add_cart:"Add",promo_title:"Your soft glow starts here.",promo_text:"Enjoy a special offer to begin your Niffalla ritual.",promo_use:"Use code",copy:"Copy Code",routine_title:"A little ritual, a little more glow.",step1:"Cleanse",step1_text:"Begin by gently cleansing your face.",step2:"Prepare",step2_text:"Refresh and prepare skin with toner.",step3:"Treat",step3_text:"Apply serum as your focused treatment step.",step4:"Moisturize",step4_text:"Lock in moisture for lasting comfort.",journal_title:"A little note for your skin.",read_more:"Read more →",article1:"How to build a simple skincare routine",article1_text:"You do not need many steps to start a consistent ritual.",article2:"Why your skin needs time to rest too",article2_text:"Care gently and listen to what your skin needs.",article3:"A good glow starts with little rituals",article3_text:"Make your self-care moment feel calmer and more meaningful.",newsletter_title:"A little beauty note, just for you.",subscribe:"Subscribe",cart_title:"Your Niffalla Ritual",empty_cart:"Your bag is still empty.",total:"Total",checkout:"Checkout via WhatsApp",wa_chat:"Chat with us",footer_text:"Gentle skincare ritual for your everyday glow.",privacy:"Privacy",follow:"FOLLOW THE GLOW",rights:"All rights reserved."}
};
function setLanguage(lang){state.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(dict[lang][k])el.textContent=dict[lang][k]});document.getElementById("langBtn").textContent=lang==="id"?"EN":"ID";document.documentElement.lang=lang;document.getElementById("searchInput").placeholder=lang==="id"?"Cari produk atau artikel...":"Search products or articles...";renderCart()}
document.getElementById("langBtn").onclick=()=>setLanguage(state.lang==="id"?"en":"id");

const searchPanel=document.getElementById("searchPanel"),searchInput=document.getElementById("searchInput");
document.getElementById("searchBtn").onclick=()=>{searchPanel.classList.toggle("open");if(searchPanel.classList.contains("open"))searchInput.focus()};
document.getElementById("closeSearch").onclick=()=>searchPanel.classList.remove("open");
searchInput.addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".product-card,.journal-card").forEach(card=>card.style.display=card.textContent.toLowerCase().includes(q)?"":"none")});

const drawer=document.getElementById("cartDrawer"),overlay=document.getElementById("overlay");
function toggleCart(open){drawer.classList.toggle("open",open);overlay.classList.toggle("show",open)}
document.getElementById("cartBtn").onclick=()=>toggleCart(true);document.getElementById("closeCart").onclick=()=>toggleCart(false);overlay.onclick=()=>toggleCart(false);
document.querySelectorAll(".add-btn").forEach(btn=>btn.onclick=()=>{const p=btn.dataset.product,price=+btn.dataset.price;const found=state.cart.find(x=>x.product===p);if(found)found.qty++;else state.cart.push({product:p,price,qty:1});renderCart();btn.textContent=state.lang==="id"?"Ditambahkan ✓":"Added ✓";setTimeout(()=>btn.textContent=dict[state.lang].add_cart,1100)});
function rupiah(n){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
function renderCart(){const items=document.getElementById("cartItems"),count=document.getElementById("cartCount"),total=document.getElementById("cartTotal");count.textContent=state.cart.reduce((a,x)=>a+x.qty,0);if(!state.cart.length){items.innerHTML=`<p class="empty-cart">${dict[state.lang].empty_cart}</p>`;total.textContent=rupiah(0);return}items.innerHTML=state.cart.map((x,i)=>`<div class="cart-item"><div><h4>${x.product} × ${x.qty}</h4><p>${rupiah(x.price*x.qty)}</p></div><button class="remove-btn" data-remove="${i}">Remove</button></div>`).join("");items.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.remove,1);renderCart()});total.textContent=rupiah(state.cart.reduce((a,x)=>a+x.price*x.qty,0))}
document.getElementById("checkoutBtn").onclick=()=>{if(!state.cart.length){alert(state.lang==="id"?"Keranjangmu masih kosong.":"Your cart is empty.");return}const lines=state.cart.map(x=>`- ${x.product} x${x.qty} (${rupiah(x.price*x.qty)})`).join("\n");const message=`Halo kak aku mau order skincare 1packet ya;\n\nPesanan saya:\n${lines}\n\nTotal: ${rupiah(state.cart.reduce((a,x)=>a+x.price*x.qty,0))}`;window.open(`https://wa.me/6285159977358?text=${encodeURIComponent(message)}`,"_blank")};
document.getElementById("waFloat").onclick=e=>{e.preventDefault();const message="Halo kak aku mau order skincare 1packet ya;";window.open(`https://wa.me/6285159977358?text=${encodeURIComponent(message)}`,"_blank")};
document.getElementById("copyPromo").onclick=()=>{navigator.clipboard.writeText("GLOW10");const b=document.getElementById("copyPromo");const old=b.textContent;b.textContent=state.lang==="id"?"Tersalin ✓":"Copied ✓";setTimeout(()=>b.textContent=old,1300)};
document.getElementById("newsletterForm").onsubmit=e=>{e.preventDefault();alert(state.lang==="id"?"Terima kasih! Kamu sudah berlangganan beauty note Niffalla.":"Thank you! You're now subscribed to Niffalla beauty notes.");e.target.reset()};
document.getElementById("mobileMenu").onclick=()=>document.getElementById("navLinks").classList.toggle("open");
document.querySelectorAll(".nav-links a").forEach(a=>a.onclick=()=>document.getElementById("navLinks").classList.remove("open"));
document.getElementById("year").textContent=new Date().getFullYear();